# Generated by Django 4.2.2 on 2023-06-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
