# Generated by Django 4.2.2 on 2023-06-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_author_book_image_alter_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='Название',
        ),
    ]
