# Generated by Django 4.2.2 on 2023-06-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_rename_name_book_название'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название: ', models.CharField(max_length=50)),
                ('Прикрепите фото: ', models.ImageField(upload_to='')),
            ],
        ),
    ]
