# Generated by Django 4.2.2 on 2023-06-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
