# Generated by Django 4.2.2 on 2023-06-17 10:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Введите текст: ',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
