# Generated by Django 4.2.2 on 2023-06-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_project_введите_текст_'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Введите текст: ',
            new_name='text',
        ),
    ]
