# Generated by Django 4.2.2 on 2023-06-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_rename_введите_текст__project_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Название: ',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Прикрепите фото: ',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Прикрепите фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
