# Generated by Django 4.2.2 on 2023-06-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_remove_project_название__and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Прикрепите фото'),
        ),
    ]
